package com.emarket.market.dao;

import com.emarket.market.pojo.Category;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_category
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_category
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int insert(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_category
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int insertSelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_category
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_category
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int updateByPrimaryKeySelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_category
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int updateByPrimaryKey(Category row);
}