package com.emarket.market.dao;

import com.emarket.market.pojo.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int insert(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int insertSelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int updateByPrimaryKeySelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    int updateByPrimaryKey(Order row);
}