package com.emarket.market.dao;

import com.emarket.market.pojo.PayInfo;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_pay_info
     *
     * @mbg.generated Sun Sep 22 19:22:03 AEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_pay_info
     *
     * @mbg.generated Sun Sep 22 19:22:03 AEST 2024
     */
    int insert(PayInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_pay_info
     *
     * @mbg.generated Sun Sep 22 19:22:03 AEST 2024
     */
    int insertSelective(PayInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_pay_info
     *
     * @mbg.generated Sun Sep 22 19:22:03 AEST 2024
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_pay_info
     *
     * @mbg.generated Sun Sep 22 19:22:03 AEST 2024
     */
    int updateByPrimaryKeySelective(PayInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_pay_info
     *
     * @mbg.generated Sun Sep 22 19:22:03 AEST 2024
     */
    int updateByPrimaryKey(PayInfo row);
}