package com.emarket.market.dao;

import com.emarket.market.pojo.Shipping;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_shipping
     *
     * @mbg.generated Fri Nov 15 12:17:43 AEDT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_shipping
     *
     * @mbg.generated Fri Nov 15 12:17:43 AEDT 2024
     */
    int insert(Shipping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_shipping
     *
     * @mbg.generated Fri Nov 15 12:17:43 AEDT 2024
     */
    int insertSelective(Shipping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_shipping
     *
     * @mbg.generated Fri Nov 15 12:17:43 AEDT 2024
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_shipping
     *
     * @mbg.generated Fri Nov 15 12:17:43 AEDT 2024
     */
    int updateByPrimaryKeySelective(Shipping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emarket_shipping
     *
     * @mbg.generated Fri Nov 15 12:17:43 AEDT 2024
     */
    int updateByPrimaryKey(Shipping row);
}