package com.emarket.market.pojo;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_category.id
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_category.parent_id
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_category.name
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_category.status
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_category.sort_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_category.create_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_category.update_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emarket_category.id
     *
     * @return the value of emarket_category.id
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emarket_category.id
     *
     * @param id the value for emarket_category.id
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emarket_category.parent_id
     *
     * @return the value of emarket_category.parent_id
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emarket_category.parent_id
     *
     * @param parentId the value for emarket_category.parent_id
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emarket_category.name
     *
     * @return the value of emarket_category.name
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emarket_category.name
     *
     * @param name the value for emarket_category.name
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emarket_category.status
     *
     * @return the value of emarket_category.status
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emarket_category.status
     *
     * @param status the value for emarket_category.status
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emarket_category.sort_order
     *
     * @return the value of emarket_category.sort_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emarket_category.sort_order
     *
     * @param sortOrder the value for emarket_category.sort_order
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emarket_category.create_time
     *
     * @return the value of emarket_category.create_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emarket_category.create_time
     *
     * @param createTime the value for emarket_category.create_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emarket_category.update_time
     *
     * @return the value of emarket_category.update_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emarket_category.update_time
     *
     * @param updateTime the value for emarket_category.update_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}