package com.emarket.market.pojo;

import lombok.Data;

import java.util.Date;

@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.id
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.username
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.password
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.email
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.phone
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.question
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.answer
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.role
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.create_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emarket_user.update_time
     *
     * @mbg.generated Sat Sep 28 17:31:14 AEST 2024
     */
    private Date updateTime;

    public User(String username, String password, String email, Integer role) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
    }

    public User() {

    }
}